#!/usr/bin/env bash

# Create a tmp-working-dir and navigate into it
mkdir -p /tmp/yay_install
cd /tmp/yay_install

# Install build dependencies if the 'base-devel' group isn't installed
sudo pacman -Sy --noconfirm --needed binutils make gcc fakeroot pkg-config

# Select correct yay package
case "$@" in
    "git")
        package="yay-git"
        ;;
    "bin")
        package="yay-bin"
        ;;
    *)
        package="yay"
        ;;
esac

# Download and make PKGBUILD
if [[ $(pacman -Qs yay) == "" ]]; then
    curl https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=${package} > PKGBUILD
    makepkg -si --needed --noconfirm
fi

# Clean up
cd ~
rm -rf /tmp/yay_install
